### ISSUE TITLE
Error When Running Badsecrets

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/badsecrets#124]
```
Traceback (most recent call last):
  File "/home/bls/.local/bin/badsecrets", line 5, in <module>
    from badsecrets.examples.cli import main
  File "/home/bls/.local/pipx/venvs/badsecrets/lib/python3.12/site-packages/badsecrets/examples/cli.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

OS: Arch Linux
Python version: 3.12
Install method: pipx

**Comment by liquidsec** [comment]
pkg_resources was only being used to display the version, and had a lot of problems with python 3.12. I found an alternative solution that allowed me to remove this dependency which should correct the problem.

**Comment by liquidsec** [comment]
https://github.com/blacklanternsecurity/badsecrets/pull/126

**Comment by liquidsec** [comment]
@TheTechromancer if you get a chance, can you confirm https://github.com/blacklanternsecurity/badsecrets/pull/126 fixes your issue?

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/badsecrets/pull/126
