### ISSUE TITLE
How to install...lol ;)

### ISSUE THREAD

**Issue by evalihub** [blacklanternsecurity/badsecrets#47]

**Comment by liquidsec** [comment]
Depending on how you are using it, you can just do a ` git clone https://github.com/blacklanternsecurity/badsecrets.git` and run from that directory, but there is also a pip package you can install with `pip install badsecrets`. I'll add something to the readme to make that a bit clearer.

**Comment by evalihub** [comment]
Thank you for being kind to us noobies :)
