### ISSUE TITLE
JWT algorithm RS256 throw error

### ISSUE THREAD

**Issue by iamyuthan** [blacklanternsecurity/badsecrets#89]
Badsecrets throws error in kali linux when attempting to decode a JWT signature with RS256 algorithm as shown below.
![image](https://github.com/blacklanternsecurity/badsecrets/assets/83505381/31df9a22-93a3-43b6-9a02-3204ac3701fc)

**Comment by liquidsec** [comment]
Hi, thanks for reporting this. I have a fix which is currently in the dev branch and will be merged to main soon.

https://github.com/blacklanternsecurity/badsecrets/pull/90
